[package]
name = "sodoku"
version = "0.1.0"
authors = ["laddertheory"]
repository = "https://github.com/LadderTheory/sodoku_rust.git"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
clap = "2.33.3"